### ISSUE TITLE
plugins are not typed as multiple values

### ISSUE THREAD

**Issue by Shinigami92** [memotux/nuxt-quasar#2]
https://github.com/memotux/nuxt-quasar/blob/f8dc8e92129085185ce61b85f0f92537e2fa0de1/src/module.ts#L11

I assume this should be `plugins: Array<'AddressbarColor' | 'AppFullscreen' | 'AppVisibility' | 'BottomSheet' | 'Dialog' | 'LoadingBar' | 'Loading' | 'Notify' | 'LocalStorage' | 'SessionStorage'>` instead?

**Comment by memotux** [comment]
Thank you. Your suggest its more explicit. I will modify it in the next release.

**Comment by memotux** [comment]
Updated in v1.0.11
