### ISSUE TITLE
Vitest support?

### ISSUE THREAD

**Issue by frisch-raphael** [memotux/nuxt-quasar#3]
Hi,

First of all thanks for this module.
I'm trying to do add unit testing based on Vitest, but to no avail yet.
I tried several things, from using installQuasarPlugin() as per this documentation 
https://github.com/quasarframework/quasar-testing/tree/dev/packages/unit-vitest

Also tried to follow the answer on this stackoverflow post :
https://stackoverflow.com/questions/71486252/vitest-integration-with-quasar

But I still don't get the full html of the quasar components in my tests.
Here's an example of what I tried

```import { DataIds } from '~~/tests/data-ids'
import { mount, VueWrapper } from '@vue/test-utils'
import { selector } from '~~/tests/test-utils'
import TileCard from '~~/components/layout/resource/TileCard.vue'
import { mockEngagements } from '~~/dtos/engagement.mock'
import { engagementColumns } from '~~/components/layout/engagement/table/engagement-table-columns'
import Quasar from 'quasar'
import { describe, beforeEach, test, expect } from 'vitest'
import { installQuasarPlugin } from '@quasar/quasar-app-extension-testing-unit-vitest'
installQuasarPlugin()

let wrapper: VueWrapper<any>
describe('the TileCard', () => {
  beforeEach(() => {
    wrapper = mount(TileCard, {
      props: {
        resource: mockEngagements[0],
        columns: engagementColumns,
      },
    })
  })

  test('checkbox works', () => {
    const html = wrapper.html({ raw: false })
    console.debug(html) 
    const checkbox = wrapper.find(selector(DataIds.ResourceTileCardCheckbox) + ' .q-checkbox__inner')
    expect(checkbox.exists()).toBe(true)
    expect(checkbox.element.checked).toBe(false)
    checkbox.trigger('click')
    expect(checkbox.element.checked).toBe(true)
  })
})
```

I'm getting this error

![image](https://user-images.githubusercontent.com/3451172/230799204-eb84e048-a93d-4847-a374-7106e4f713e3.png)

Any idea on how to proceed?

**Comment by memotux** [comment]
Sorry, but I have don't know about testing features.
